export type MoneyStatus = "planned" | "paid" | "received" | "overdue" | "cancelled";
export type TransactionType = "income" | "expense" | "card" | "transfer";
export type Recurrence = "none" | "monthly";

export interface AppUser { uid: string; name: string; email: string; householdId: string; }
export interface Account { id: string; name: string; bank: string; holder: string; balance: number; color?: string; }
export interface Card { id: string; name: string; bank: string; holder: string; limit: number; closingDay: number; dueDay: number; }
export interface Transaction {
  id: string;
  description: string;
  amountPlanned: number;
  amountActual?: number;
  type: TransactionType;
  status: MoneyStatus;
  category: string;
  dueDate: string;
  paidDate?: string;
  accountId?: string;
  fromAccountId?: string;
  toAccountId?: string;
  fromAccountName?: string;
  toAccountName?: string;
  cardId?: string;
  recurrence?: Recurrence;
  installmentGroupId?: string;
  installmentNumber?: number;
  installmentTotal?: number;
  notes?: string;
  createdBy: string;
  createdAt?: unknown;
  invoiceMonth?: string;
  purchaseDate?: string;
  sourceCardId?: string;
  autoGenerated?: boolean;
  isCardInvoice?: boolean;
}
export interface Goal { id: string; name: string; target: number; current: number; targetDate?: string; icon?: string; }

export interface MonthlyClosing {
  id: string;
  month: string;
  incomePlanned: number;
  incomeActual: number;
  expensePlanned: number;
  expenseActual: number;
  plannedBalance: number;
  actualBalance: number;
  pendingExpenses: number;
  pendingIncome: number;
  bankBalance: number;
  transactionCount: number;
  pendingCount: number;
  accountBalances: Array<{ id: string; name: string; balance: number }>;
  closedBy: string;
  createdAt?: unknown;
  updatedAt?: unknown;
}
