"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createUserWithEmailAndPassword, deleteUser, signInWithEmailAndPassword, updateProfile } from "firebase/auth";
import { doc, serverTimestamp, setDoc, updateDoc } from "firebase/firestore";
import { WalletCards, ShieldCheck, Sparkles } from "lucide-react";
import { getFirebaseServices } from "@/lib/firebase";
import { useAuth } from "@/components/AuthProvider";
const makeCode=()=>Math.random().toString(36).slice(2,10).toUpperCase();
export default function LoginPage(){
 const {user,loading,firebaseConfigured}=useAuth(); const router=useRouter(); const [mode,setMode]=useState<"login"|"signup">("login"); const [join,setJoin]=useState(false); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [familyId,setFamilyId]=useState(""); const [inviteCode,setInviteCode]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{if(!loading&&user)router.replace("/dashboard")},[loading,user,router]);
 async function submit(e:React.FormEvent){e.preventDefault();setError("");const s=getFirebaseServices();if(!s){setError("Não foi possível inicializar o Firebase.");return;}setBusy(true);try{if(mode==="login"){await signInWithEmailAndPassword(s.auth,email,password);}else{const cred=await createUserWithEmailAndPassword(s.auth,email,password);try{await updateProfile(cred.user,{displayName:name});let householdId="";if(join){householdId=familyId.trim();await updateDoc(doc(s.db,"households",householdId),{[`members.${cred.user.uid}`]:true,joinCodeAttempt:inviteCode.trim().toUpperCase()});}else{householdId=crypto.randomUUID();await setDoc(doc(s.db,"households",householdId),{name:`Família de ${name}`,members:{[cred.user.uid]:true},inviteCode:makeCode(),createdAt:serverTimestamp()});}await setDoc(doc(s.db,"users",cred.user.uid),{name,email,householdId,createdAt:serverTimestamp()});}catch(inner){await deleteUser(cred.user);throw inner;}}router.replace("/dashboard");}catch(err:any){setError(err?.code==="auth/invalid-credential"?"E-mail ou senha inválidos.":err?.code==="permission-denied"?"ID da família ou código de convite inválido.":err?.message||"Não foi possível entrar.");}finally{setBusy(false)}}
 return <main className="login-page"><section className="login-showcase"><div className="logo-big"><WalletCards/> NexFin</div><div className="showcase-copy"><span className="eyebrow"><Sparkles size={15}/> Finanças a dois, sem complicação</span><h1>Planejem hoje.<br/>Vivam melhor amanhã.</h1><p>Contas, cartões, parcelas, metas e projeções em um só lugar para o casal.</p></div><div className="showcase-card"><ShieldCheck/><div><strong>Dois logins, uma vida financeira</strong><span>Cada pessoa usa seu próprio e-mail e senha, mas os dados ficam na mesma família.</span></div></div></section>
 <section className="login-panel"><form onSubmit={submit} className="login-form"><div><h2>{mode==="login"?"Bem-vindo de volta":"Criar acesso"}</h2><p>{mode==="login"?"Acesse o financeiro compartilhado.":join?"Use o ID e o código enviados pelo seu parceiro.":"Crie a família financeira e depois convide seu parceiro."}</p></div>
 {!firebaseConfigured&&<div className="notice">Firebase não pôde ser inicializado.</div>}
 {mode==="signup"&&<><div className="segmented"><button type="button" className={!join?"selected":""} onClick={()=>setJoin(false)}>Criar família</button><button type="button" className={join?"selected":""} onClick={()=>setJoin(true)}>Entrar com convite</button></div><label>Seu nome<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Seu nome"/></label>{join&&<div className="form-grid"><label>ID da família<input required value={familyId} onChange={e=>setFamilyId(e.target.value)} placeholder="Cole o ID"/></label><label>Código de convite<input required value={inviteCode} onChange={e=>setInviteCode(e.target.value)} placeholder="Ex.: A1B2C3D4"/></label></div>}</>}
 <label>E-mail<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@email.com"/></label><label>Senha<input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label>
 {error&&<div className="error-box">{error}</div>}<button className="primary-btn wide" disabled={busy}>{busy?"Aguarde...":mode==="login"?"Entrar":"Criar acesso"}</button><button type="button" className="text-btn" onClick={()=>setMode(mode==="login"?"signup":"login")}>{mode==="login"?"Primeiro acesso? Criar conta":"Já tenho conta"}</button></form></section></main>
}
