"use client";
import { useMemo } from "react";
import { ArrowDownRight, ArrowUpRight, CircleDollarSign, Clock3, PiggyBank, TrendingUp } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import AppShell from "@/components/AppShell"; import StatCard from "@/components/StatCard"; import Empty from "@/components/Empty"; import { useHouseholdData } from "@/components/useHouseholdData"; import { brl, monthKey, monthLabel, summarize, savingsInsights } from "@/lib/finance";
export default function Dashboard(){const {transactions,goals}=useHouseholdData(); const mk=monthKey(); const current=useMemo(()=>transactions.filter(t=>t.dueDate?.startsWith(mk)),[transactions,mk]); const sum=summarize(current); const insight=savingsInsights(current,sum.incomePlanned); const chart=useMemo(()=>{const m=new Map<string,{cat:string,valor:number}>();current.filter(t=>t.type!=="income").forEach(t=>{const x=m.get(t.category)||{cat:t.category,valor:0};x.valor+=t.amountActual??t.amountPlanned;m.set(t.category,x)});return [...m.values()].sort((a,b)=>b.valor-a.valor).slice(0,6)},[current]);
 return <AppShell title="Visão geral" subtitle={`Resumo de ${monthLabel()}`}><div className="stats-grid"><StatCard label="Entradas previstas" value={brl(sum.incomePlanned)} hint={`${brl(sum.incomeActual)} recebido`} icon={<ArrowUpRight/>}/><StatCard label="Despesas previstas" value={brl(sum.expensePlanned)} hint={`${brl(sum.expenseActual)} pago`} icon={<ArrowDownRight/>}/><StatCard label="Saldo previsto" value={brl(sum.plannedBalance)} hint="Depois dos compromissos" icon={<CircleDollarSign/>}/><StatCard label="Ainda a pagar" value={brl(sum.pending)} hint="Compromissos do mês" icon={<Clock3/>}/></div>
 <div className="two-col"><section className="panel"><div className="panel-head"><div><h2>Para onde o dinheiro está indo</h2><p>Despesas por categoria neste mês.</p></div></div>{chart.length?<div className="chart-wrap"><ResponsiveContainer width="100%" height={290}><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="cat" tickLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip formatter={(v)=>brl(Number(v))}/><Bar dataKey="valor" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div>:<Empty/>}</section>
 <section className="panel insight-card"><div className="insight-icon"><TrendingUp/></div><span className="eyebrow">Oportunidade de economia</span><h2>{insight.realisticMonthly>0?`Vocês podem testar uma economia de ${brl(insight.realisticMonthly)}/mês`:`Cadastre despesas para receber dicas personalizadas`}</h2><p>{insight.realisticMonthly>0?`Aplicando pequenos ajustes nas categorias variáveis, a projeção em 12 meses é de ${brl(insight.yearProjection)}.`:"O sistema compara categorias e transforma pequenos cortes em projeções mensais e anuais."}</p><a href="/insights" className="soft-btn">Ver análise completa</a></section></div>
 <div className="two-col"><section className="panel"><div className="panel-head"><div><h2>Próximos compromissos</h2><p>O que ainda vence neste mês.</p></div></div><div className="transaction-list">{current.filter(t=>t.status==="planned").sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,6).map(t=><div className="transaction-row" key={t.id}><div className="tx-icon">{t.type==="income"?<ArrowUpRight/>:<ArrowDownRight/>}</div><div className="tx-main"><strong>{t.description}</strong><span>{new Date(t.dueDate+"T12:00").toLocaleDateString("pt-BR")} · {t.category}{t.installmentTotal?` · ${t.installmentNumber}/${t.installmentTotal}`:""}</span></div><strong>{brl(t.amountPlanned)}</strong></div>)}{!current.some(t=>t.status==="planned")&&<Empty text="Nenhum compromisso pendente."/>}</div></section>
 <section className="panel"><div className="panel-head"><div><h2>Caixinhas</h2><p>Objetivos que vocês estão construindo juntos.</p></div><a href="/metas">Ver todas</a></div>{goals.length?goals.slice(0,4).map(g=>{const pct=Math.min(100,g.target?g.current/g.target*100:0);return <div className="goal-mini" key={g.id}><div><strong>{g.icon||"🎯"} {g.name}</strong><span>{brl(g.current)} de {brl(g.target)}</span></div><div className="progress"><i style={{width:`${pct}%`}}/></div><small>{pct.toFixed(0)}%</small></div>}):<Empty text="Crie sua primeira caixinha."/>}</section></div></AppShell>}
