"use client";
import { useMemo } from "react";
import { ArrowDownRight, ArrowUpRight, CircleDollarSign, Clock3, PiggyBank, TrendingUp, WalletCards } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Line, ComposedChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import AppShell from "@/components/AppShell";
import StatCard from "@/components/StatCard";
import Empty from "@/components/Empty";
import { useHouseholdData } from "@/components/useHouseholdData";
import { brl, monthKey, monthLabel, monthLabelFromKey, shiftMonthKey, summarize, savingsInsights } from "@/lib/finance";

export default function Dashboard(){
 const {transactions,goals,accounts}=useHouseholdData();
 const mk=monthKey();
 const current=useMemo(()=>transactions.filter(t=>t.dueDate?.startsWith(mk)),[transactions,mk]);
 const sum=summarize(current);
 const insight=savingsInsights(current,sum.incomePlanned);
 const accountsBalance=accounts.reduce((s,a)=>s+Number(a.balance||0),0);
 const freeProjected=accountsBalance + sum.incomePending - sum.pending;
 const nextKey=shiftMonthKey(mk,1);
 const nextTx=useMemo(()=>transactions.filter(t=>t.dueDate?.startsWith(nextKey)),[transactions,nextKey]);
 const nextSum=summarize(nextTx);
 const nextCommitment=nextSum.incomePlanned?Math.min(100,(nextSum.expensePlanned/nextSum.incomePlanned)*100):0;
 const chart=useMemo(()=>{const m=new Map<string,{cat:string,valor:number}>();current.filter(t=>t.type!=="income").forEach(t=>{const x=m.get(t.category)||{cat:t.category,valor:0};x.valor+=t.amountActual??t.amountPlanned;m.set(t.category,x)});return [...m.values()].sort((a,b)=>b.valor-a.valor).slice(0,6)},[current]);
 const projection=useMemo(()=>Array.from({length:6},(_,i)=>{const key=shiftMonthKey(mk,i);const s=summarize(transactions.filter(t=>t.dueDate?.startsWith(key)));return {mes:monthLabelFromKey(key).split(" de ")[0].slice(0,3),entradas:s.incomePlanned,despesas:s.expensePlanned,saldo:s.plannedBalance};}),[transactions,mk]);
 const nextTop=useMemo(()=>nextTx.filter(t=>t.type!=="income"&&t.status!=="cancelled").sort((a,b)=>b.amountPlanned-a.amountPlanned).slice(0,4),[nextTx]);
 const balanceDiff=nextSum.plannedBalance-sum.plannedBalance;

 return <AppShell title="Visão geral" subtitle={`Resumo de ${monthLabel()}`}>
  <div className="dashboard-balance-hero"><div><span className="eyebrow">Posição financeira do casal</span><h2>{brl(accountsBalance)}</h2><p>Saldo atual somado das contas cadastradas.</p></div><div className="hero-balance-metrics"><div><span>Saldo livre projetado</span><strong className={freeProjected>=0?"positive-text":"negative-text"}>{brl(freeProjected)}</strong><small>Saldo atual + entradas pendentes − contas a pagar</small></div><div><span>Resultado previsto do mês</span><strong>{brl(sum.plannedBalance)}</strong><small>{sum.incomePlanned?`${((sum.expensePlanned/sum.incomePlanned)*100).toFixed(0)}% da renda comprometida`:"Cadastre as receitas do mês"}</small></div></div><WalletCards/></div>
  <div className="stats-grid"><StatCard label="Entradas previstas" value={brl(sum.incomePlanned)} hint={`${brl(sum.incomeActual)} recebido`} icon={<ArrowUpRight/>}/><StatCard label="Despesas previstas" value={brl(sum.expensePlanned)} hint={`${brl(sum.expenseActual)} pago`} icon={<ArrowDownRight/>}/><StatCard label="Saldo previsto" value={brl(sum.plannedBalance)} hint={`Realizado: ${brl(sum.actualBalance)}`} icon={<CircleDollarSign/>}/><StatCard label="Ainda a pagar" value={brl(sum.pending)} hint={`${brl(sum.incomePending)} ainda a receber`} icon={<Clock3/>}/></div>
  <div className="dashboard-main-grid"><section className="panel"><div className="panel-head"><div><h2>Fluxo financeiro projetado</h2><p>Entradas, despesas e saldo dos próximos 6 meses com base no que já foi provisionado.</p></div><span className="projection-badge">6 meses</span></div><div className="chart-wrap forecast-chart"><ResponsiveContainer width="100%" height={310}><ComposedChart data={projection}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="mes" tickLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip formatter={(v)=>brl(Number(v))}/><Bar dataKey="entradas" name="Entradas" radius={[7,7,0,0]}/><Bar dataKey="despesas" name="Despesas" radius={[7,7,0,0]}/><Line type="monotone" dataKey="saldo" name="Saldo" strokeWidth={3} dot={{r:4}}/></ComposedChart></ResponsiveContainer></div></section>
  <section className="panel next-month-card"><div className="panel-head"><div><span className="eyebrow">Próximo mês</span><h2>Projeção de {monthLabelFromKey(nextKey)}</h2><p>Calculada automaticamente a partir das contas recorrentes, parcelas e receitas provisionadas.</p></div></div><div className="next-month-balance"><span>Saldo projetado</span><strong className={nextSum.plannedBalance>=0?"positive-text":"negative-text"}>{brl(nextSum.plannedBalance)}</strong><small className={balanceDiff>=0?"positive-text":"negative-text"}>{balanceDiff>=0?"+":""}{brl(balanceDiff)} vs. este mês</small></div><div className="next-month-grid"><div><span>Entradas</span><strong>{brl(nextSum.incomePlanned)}</strong></div><div><span>Despesas</span><strong>{brl(nextSum.expensePlanned)}</strong></div></div><div className="commitment"><div><span>Comprometimento da renda</span><strong>{nextCommitment.toFixed(0)}%</strong></div><div className="progress"><i style={{width:`${nextCommitment}%`}}/></div></div><div className="next-top-list">{nextTop.length?nextTop.map(t=><div key={t.id}><span>{t.description}{t.installmentTotal?` · ${t.installmentNumber}/${t.installmentTotal}`:""}</span><strong>{brl(t.amountPlanned)}</strong></div>):<p>Nenhuma despesa provisionada para o próximo mês.</p>}</div></section></div>
  <div className="two-col"><section className="panel"><div className="panel-head"><div><h2>Para onde o dinheiro está indo</h2><p>Despesas por categoria neste mês.</p></div></div>{chart.length?<div className="chart-wrap"><ResponsiveContainer width="100%" height={290}><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="cat" tickLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip formatter={(v)=>brl(Number(v))}/><Bar dataKey="valor" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div>:<Empty/>}</section>
  <section className="panel insight-card"><div className="insight-icon"><TrendingUp/></div><span className="eyebrow">Oportunidade de economia</span><h2>{insight.realisticMonthly>0?`Vocês podem testar uma economia de ${brl(insight.realisticMonthly)}/mês`:`Cadastre despesas para receber dicas personalizadas`}</h2><p>{insight.realisticMonthly>0?`Aplicando pequenos ajustes nas categorias variáveis, a projeção em 12 meses é de ${brl(insight.yearProjection)}.`:"O sistema compara categorias e transforma pequenos cortes em projeções mensais e anuais."}</p><a href="/insights" className="soft-btn">Ver análise completa</a></section></div>
  <div className="two-col"><section className="panel"><div className="panel-head"><div><h2>Próximos compromissos</h2><p>O que ainda vence neste mês.</p></div></div><div className="transaction-list">{current.filter(t=>t.status==="planned").sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,6).map(t=><div className="transaction-row" key={t.id}><div className="tx-icon">{t.type==="income"?<ArrowUpRight/>:<ArrowDownRight/>}</div><div className="tx-main"><strong>{t.description}</strong><span>{new Date(t.dueDate+"T12:00").toLocaleDateString("pt-BR")} · {t.category}{t.installmentTotal?` · ${t.installmentNumber}/${t.installmentTotal}`:""}</span></div><strong>{brl(t.amountPlanned)}</strong></div>)}{!current.some(t=>t.status==="planned")&&<Empty text="Nenhum compromisso pendente."/>}</div></section>
  <section className="panel"><div className="panel-head"><div><h2>Caixinhas</h2><p>Objetivos que vocês estão construindo juntos.</p></div><a href="/metas">Ver todas</a></div>{goals.length?goals.slice(0,4).map(g=>{const pct=Math.min(100,g.target?g.current/g.target*100:0);return <div className="goal-mini" key={g.id}><div><strong>{g.icon||"🎯"} {g.name}</strong><span>{brl(g.current)} de {brl(g.target)}</span></div><div className="progress"><i style={{width:`${pct}%`}}/></div><small>{pct.toFixed(0)}%</small></div>}):<Empty text="Crie sua primeira caixinha."/>}</section></div>
 </AppShell>
}
